fragment PagesParts on Pages {
  blocks {
    __typename
    ... on PagesBlocksContent {
      heading
      body
    }
    ... on PagesBlocksFooterImage {
      footerImg
    }
    ... on PagesBlocksGallery {
      photos {
        __typename
        title
        src
      }
    }
    ... on PagesBlocksVideo {
      url
    }
  }
}
