// DO NOT MODIFY THIS FILE. This file is automatically generated by Tina
export type Maybe<T> = T | null;
export type Exact<T extends { [key: string]: unknown }> = { [K in keyof T]: T[K] };
export type MakeOptional<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]?: Maybe<T[SubKey]> };
export type MakeMaybe<T, K extends keyof T> = Omit<T, K> & { [SubKey in K]: Maybe<T[SubKey]> };
/** All built-in and custom scalars, mapped to their actual values */
export type Scalars = {
  ID: string;
  String: string;
  Boolean: boolean;
  Int: number;
  Float: number;
  /** References another document, used as a foreign key */
  Reference: any;
  JSON: any;
};



export type SystemInfo = {
  __typename?: 'SystemInfo';
  filename: Scalars['String'];
  basename: Scalars['String'];
  breadcrumbs: Array<Scalars['String']>;
  path: Scalars['String'];
  relativePath: Scalars['String'];
  extension: Scalars['String'];
  template: Scalars['String'];
  collection: Collection;
};


export type SystemInfoBreadcrumbsArgs = {
  excludeExtension?: Maybe<Scalars['Boolean']>;
};

export type PageInfo = {
  __typename?: 'PageInfo';
  hasPreviousPage: Scalars['Boolean'];
  hasNextPage: Scalars['Boolean'];
  startCursor: Scalars['String'];
  endCursor: Scalars['String'];
};

export type Node = {
  id: Scalars['ID'];
};

export type Document = {
  sys?: Maybe<SystemInfo>;
  id: Scalars['ID'];
};

/** A relay-compliant pagination connection */
export type Connection = {
  totalCount: Scalars['Int'];
};

export type Query = {
  __typename?: 'Query';
  getCollection: Collection;
  getCollections: Array<Collection>;
  node: Node;
  getDocument: DocumentNode;
  getDocumentList: DocumentConnection;
  getGlobalDocument: GlobalDocument;
  getGlobalList: GlobalConnection;
  getPagesDocument: PagesDocument;
  getPagesList: PagesConnection;
};


export type QueryGetCollectionArgs = {
  collection?: Maybe<Scalars['String']>;
};


export type QueryNodeArgs = {
  id?: Maybe<Scalars['String']>;
};


export type QueryGetDocumentArgs = {
  collection?: Maybe<Scalars['String']>;
  relativePath?: Maybe<Scalars['String']>;
};


export type QueryGetDocumentListArgs = {
  before?: Maybe<Scalars['String']>;
  after?: Maybe<Scalars['String']>;
  first?: Maybe<Scalars['Int']>;
  last?: Maybe<Scalars['Int']>;
};


export type QueryGetGlobalDocumentArgs = {
  relativePath?: Maybe<Scalars['String']>;
};


export type QueryGetGlobalListArgs = {
  before?: Maybe<Scalars['String']>;
  after?: Maybe<Scalars['String']>;
  first?: Maybe<Scalars['Int']>;
  last?: Maybe<Scalars['Int']>;
};


export type QueryGetPagesDocumentArgs = {
  relativePath?: Maybe<Scalars['String']>;
};


export type QueryGetPagesListArgs = {
  before?: Maybe<Scalars['String']>;
  after?: Maybe<Scalars['String']>;
  first?: Maybe<Scalars['Int']>;
  last?: Maybe<Scalars['Int']>;
};

export type DocumentConnectionEdges = {
  __typename?: 'DocumentConnectionEdges';
  cursor?: Maybe<Scalars['String']>;
  node?: Maybe<DocumentNode>;
};

export type DocumentConnection = Connection & {
  __typename?: 'DocumentConnection';
  pageInfo?: Maybe<PageInfo>;
  totalCount: Scalars['Int'];
  edges?: Maybe<Array<Maybe<DocumentConnectionEdges>>>;
};

export type Collection = {
  __typename?: 'Collection';
  name: Scalars['String'];
  slug: Scalars['String'];
  label: Scalars['String'];
  path: Scalars['String'];
  format?: Maybe<Scalars['String']>;
  matches?: Maybe<Scalars['String']>;
  templates?: Maybe<Array<Maybe<Scalars['JSON']>>>;
  fields?: Maybe<Array<Maybe<Scalars['JSON']>>>;
  documents: DocumentConnection;
};


export type CollectionDocumentsArgs = {
  before?: Maybe<Scalars['String']>;
  after?: Maybe<Scalars['String']>;
  first?: Maybe<Scalars['Int']>;
  last?: Maybe<Scalars['Int']>;
};

export type DocumentNode = GlobalDocument | PagesDocument;

export type GlobalHeaderNav = {
  __typename?: 'GlobalHeaderNav';
  href?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
};

export type GlobalHeader = {
  __typename?: 'GlobalHeader';
  nav?: Maybe<Array<Maybe<GlobalHeaderNav>>>;
};

export type GlobalFooterSocialGmail = {
  __typename?: 'GlobalFooterSocialGmail';
  handle?: Maybe<Scalars['String']>;
  link?: Maybe<Scalars['String']>;
};

export type GlobalFooterSocialInstagram = {
  __typename?: 'GlobalFooterSocialInstagram';
  handle?: Maybe<Scalars['String']>;
  link?: Maybe<Scalars['String']>;
};

export type GlobalFooterSocialImdb = {
  __typename?: 'GlobalFooterSocialImdb';
  handle?: Maybe<Scalars['String']>;
  link?: Maybe<Scalars['String']>;
};

export type GlobalFooterSocial = {
  __typename?: 'GlobalFooterSocial';
  gmail?: Maybe<GlobalFooterSocialGmail>;
  instagram?: Maybe<GlobalFooterSocialInstagram>;
  imdb?: Maybe<GlobalFooterSocialImdb>;
};

export type GlobalFooter = {
  __typename?: 'GlobalFooter';
  social?: Maybe<GlobalFooterSocial>;
};

export type Global = {
  __typename?: 'Global';
  header?: Maybe<GlobalHeader>;
  footer?: Maybe<GlobalFooter>;
};

export type GlobalDocument = Node & Document & {
  __typename?: 'GlobalDocument';
  id: Scalars['ID'];
  sys: SystemInfo;
  data: Global;
  form: Scalars['JSON'];
  values: Scalars['JSON'];
  dataJSON: Scalars['JSON'];
};

export type GlobalConnectionEdges = {
  __typename?: 'GlobalConnectionEdges';
  cursor?: Maybe<Scalars['String']>;
  node?: Maybe<GlobalDocument>;
};

export type GlobalConnection = Connection & {
  __typename?: 'GlobalConnection';
  pageInfo?: Maybe<PageInfo>;
  totalCount: Scalars['Int'];
  edges?: Maybe<Array<Maybe<GlobalConnectionEdges>>>;
};

export type PagesBlocksPhotosPhotos = {
  __typename?: 'PagesBlocksPhotosPhotos';
  photo?: Maybe<Scalars['String']>;
};

export type PagesBlocksPhotos = {
  __typename?: 'PagesBlocksPhotos';
  photos?: Maybe<Array<Maybe<PagesBlocksPhotosPhotos>>>;
};

export type PagesBlocksContent = {
  __typename?: 'PagesBlocksContent';
  heading?: Maybe<Scalars['String']>;
  body?: Maybe<Scalars['String']>;
};

export type PagesBlocksFooterImage = {
  __typename?: 'PagesBlocksFooterImage';
  footerImg?: Maybe<Scalars['String']>;
};

export type PagesBlocks = PagesBlocksPhotos | PagesBlocksContent | PagesBlocksFooterImage;

export type Pages = {
  __typename?: 'Pages';
  blocks?: Maybe<Array<Maybe<PagesBlocks>>>;
};

export type PagesDocument = Node & Document & {
  __typename?: 'PagesDocument';
  id: Scalars['ID'];
  sys: SystemInfo;
  data: Pages;
  form: Scalars['JSON'];
  values: Scalars['JSON'];
  dataJSON: Scalars['JSON'];
};

export type PagesConnectionEdges = {
  __typename?: 'PagesConnectionEdges';
  cursor?: Maybe<Scalars['String']>;
  node?: Maybe<PagesDocument>;
};

export type PagesConnection = Connection & {
  __typename?: 'PagesConnection';
  pageInfo?: Maybe<PageInfo>;
  totalCount: Scalars['Int'];
  edges?: Maybe<Array<Maybe<PagesConnectionEdges>>>;
};

export type Mutation = {
  __typename?: 'Mutation';
  addPendingDocument: DocumentNode;
  updateDocument: DocumentNode;
  updateGlobalDocument: GlobalDocument;
  updatePagesDocument: PagesDocument;
};


export type MutationAddPendingDocumentArgs = {
  collection: Scalars['String'];
  relativePath: Scalars['String'];
  template?: Maybe<Scalars['String']>;
};


export type MutationUpdateDocumentArgs = {
  collection: Scalars['String'];
  relativePath: Scalars['String'];
  params: DocumentMutation;
};


export type MutationUpdateGlobalDocumentArgs = {
  relativePath: Scalars['String'];
  params: GlobalMutation;
};


export type MutationUpdatePagesDocumentArgs = {
  relativePath: Scalars['String'];
  params: PagesMutation;
};

export type DocumentMutation = {
  global?: Maybe<GlobalMutation>;
  pages?: Maybe<PagesMutation>;
};

export type GlobalHeaderNavMutation = {
  href?: Maybe<Scalars['String']>;
  label?: Maybe<Scalars['String']>;
};

export type GlobalHeaderMutation = {
  nav?: Maybe<Array<Maybe<GlobalHeaderNavMutation>>>;
};

export type GlobalFooterSocialGmailMutation = {
  handle?: Maybe<Scalars['String']>;
  link?: Maybe<Scalars['String']>;
};

export type GlobalFooterSocialInstagramMutation = {
  handle?: Maybe<Scalars['String']>;
  link?: Maybe<Scalars['String']>;
};

export type GlobalFooterSocialImdbMutation = {
  handle?: Maybe<Scalars['String']>;
  link?: Maybe<Scalars['String']>;
};

export type GlobalFooterSocialMutation = {
  gmail?: Maybe<GlobalFooterSocialGmailMutation>;
  instagram?: Maybe<GlobalFooterSocialInstagramMutation>;
  imdb?: Maybe<GlobalFooterSocialImdbMutation>;
};

export type GlobalFooterMutation = {
  social?: Maybe<GlobalFooterSocialMutation>;
};

export type GlobalMutation = {
  header?: Maybe<GlobalHeaderMutation>;
  footer?: Maybe<GlobalFooterMutation>;
};

export type PagesBlocksPhotosPhotosMutation = {
  photo?: Maybe<Scalars['String']>;
};

export type PagesBlocksPhotosMutation = {
  photos?: Maybe<Array<Maybe<PagesBlocksPhotosPhotosMutation>>>;
};

export type PagesBlocksContentMutation = {
  heading?: Maybe<Scalars['String']>;
  body?: Maybe<Scalars['String']>;
};

export type PagesBlocksFooterImageMutation = {
  footerImg?: Maybe<Scalars['String']>;
};

export type PagesBlocksMutation = {
  photos?: Maybe<PagesBlocksPhotosMutation>;
  content?: Maybe<PagesBlocksContentMutation>;
  footerImage?: Maybe<PagesBlocksFooterImageMutation>;
};

export type PagesMutation = {
  blocks?: Maybe<Array<Maybe<PagesBlocksMutation>>>;
};

